services:
  postgres:
    container_name: nest-clean-pg
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest_clean
    #   PGDATA: /data/postgres
    # volumes:
    #   - ./data/pg:/data/postgres